### ISSUE TITLE
fatal error: 'openssl/opensslv.h: No such file or directory' while building '_openssl' extension during vagrant controller provisioning.

### ISSUE THREAD

**Issue by teterkin** [lekum/introduction-to-ansible#1]
```
    controller: building '_openssl' extension
    controller:
    controller: creating build/temp.linux-x86_64-2.7/build
    controller:
    controller: creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    controller:
    controller: x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    controller:
    controller: build/temp.linux-x86_64-2.7/_openssl.c:498:30: fatal error: openssl/opensslv.h: No such file or directory
    controller:
    controller:  #include <openssl/opensslv.h>
    controller:
    controller:                               ^
    controller:
    controller: compilation terminated.
    controller:
    controller: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    controller:
    controller: ----------------------------------------
```
